package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;

public class MainController {
	@FXML
	private TextField playerFirstName;
	@FXML
	private TextField playerLastName;
	@FXML
	private TextField playerAddress;
	@FXML
	private TextField playerProvince;
	@FXML
	private TextField playerPostalCode;
	@FXML
	private TextField playerPhoneNumber;
	@FXML
	private TextField playerID;
	@FXML
	private Button updateInfo;
	@FXML
	private DatePicker gamePlayedDate;
	@FXML
	private TextField gameScore;
	@FXML
	private TextField gameTitle;
	@FXML
	private Button createPlayer;
	@FXML
	private Button displayPlayer;

	// Event Listener on Button[#updateInfo].onAction
	@FXML
	public void updateinfo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#createPlayer].onAction
	@FXML
	public void createplayer(ActionEvent event) {
		// TODO Autogenerated
		String playerFName = playerFirstName.getText();
		String playerLName = playerLastName.getText();
		String playerAdd = playerAddress.getText();
		String playerProv = playerProvince.getText();
		String playerPcode = playerPostalCode.getText();
		String playerPNumber = playerPhoneNumber.getText();
		String playerPID = playerID.getText();
		String gmTitle = gameTitle.getText();
		String gmScore = gameScore.getText();
		String gmPlayedDate = String.valueOf(gamePlayedDate.getValue());
	}
	// Event Listener on Button[#displayPlayer].onAction
	@FXML
	public void displayplayer(ActionEvent event) {
		// TODO Autogenerated
	}
}
